/*
 * FRC 2026 REBUILT — closed-form shooter aim lookup  (Alpha Sim, V3.1 fit)
 * ---------------------------------------------------------------------------
 * Input : horizontal distance d (m) from the ball's EXIT point to the HUB center.
 * Output: hood angle (deg) + flywheel SURFACE (rim) linear speed (m/s).
 *
 * Field calibration is ONE number: kSpeed. Nothing else needs tuning at an event.
 *
 * How the coefficients were derived: research_report.html §2–5. They were
 * generated by scripts/generate_coefficients.py at SHOOTER_HEIGHT_M (below);
 * the height is BAKED INTO the polynomials — editing that constant alone does
 * nothing at runtime. To retarget a different exit height, rerun the generator
 * and paste the new a/b/c.
 *
 * Java 17 (WPILib 2024+).  Run once < 1 µs — call it every loop, no caching needed.
 */
public final class ShooterAim {

    /** Ball exit height above carpet (m) the coefficients were generated at.
     *  Provenance ONLY — not a runtime input (it is baked into the coeffs below).
     *  To change height:  python scripts/generate_coefficients.py --shooter-height <h>
     *  then paste the new coefficients into the two methods below. */
    public static final double SHOOTER_HEIGHT_M = 0.50;

    /** Valid distance range of the fit (m). Outside this the polynomial
     *  extrapolates and the hood curve (a U) turns back up — inputs are clamped. */
    public static final double D_MIN = 1.5, D_MAX = 5.0;

    // ── THE field-calibration knob ──────────────────────────────────────────
    //  Single gain on flywheel speed. Start at 1.0.
    //    balls landing SHORT → raise  (e.g. 1.03)
    //    balls landing LONG  → lower  (e.g. 0.97)
    //  Absorbs wheel slip, ball compression, battery voltage and air-model error
    //  in one number — the only thing you should touch at a competition.
    public static double kSpeed = 1.00;

    /** Hood angle (deg; 90° = straight down) for distance d (m). */
    public static double hoodAngleDeg(double d) {
        d = clamp(d);
        return 0.887787 * d*d - 10.549949 * d + 86.441900;
    }

    /** Flywheel SURFACE (rim) linear speed (m/s) for distance d (m).
     *  Convert to RPM with your wheel diameter D (m): rpm = v / (Math.PI * D) * 60. */
    public static double flywheelSpeedMps(double d) {
        d = clamp(d);
        return kSpeed * (0.016170 * d*d + 0.717698 * d + 6.404844);
    }

    /** Convenience: both outputs at once. */
    public static Aim aimFor(double d) {
        return new Aim(hoodAngleDeg(d), flywheelSpeedMps(d));
    }

    /** (hoodAngleDeg, flywheelSpeedMps) */
    public record Aim(double hoodAngleDeg, double flywheelSpeedMps) {}

    private static double clamp(double d) { return Math.max(D_MIN, Math.min(D_MAX, d)); }

    private ShooterAim() {}

    // Quick sanity demo:  javac ShooterAim.java && java ShooterAim
    public static void main(String[] args) {
        for (double d : new double[]{1.5, 2.0, 3.0, 4.0, 5.0}) {
            Aim a = aimFor(d);
            System.out.printf("d=%.1f m  ->  hood %6.2f deg   flywheel %6.2f m/s%n",
                              d, a.hoodAngleDeg(), a.flywheelSpeedMps());
        }
    }
}
